# Generated by Django 2.0.5 on 2018-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitymanager',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
