# Generated by Django 2.0.5 on 2018-05-11 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FMApp', '0003_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comp_requests', to='FMApp.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='apartment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='FMApp.Apartment'),
            preserve_default=False,
        ),
    ]
